version: '3.7'
services:
  arangodb_container:
    image: arangodb/arangodb:latest
    restart: unless-stopped
    environment:
      ARANGO_NO_AUTH: 1
      ARANGO_ROOT_PASSWORD: your-password-here
    ports:
      - 8529:8529
    volumes:
      - ./storage/arango:/var/lib/arangodb3
