# A giant pile of containerized services for the built-in shims.
#
# These are ABSOLUTELY NOT appropriate for production use; these are here
# to give automated tests a consistent baseline.

services:
  arangodb:
    image: arangodb/arangodb
    restart: unless-stopped
    environment:
      ARANGO_NO_AUTH: 1
      ARANGO_ROOT_PASSWORD: your-password-here
    ports:
      - 8529:8529
#    volumes:
#      - ./storage/arangodb:/var/lib/arangodb3
  postgres:
    image: pgvector/pgvector:16
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: ''
    ports:
      - 5432:5432
#    volumes:
#      - ./storage/postgres:/var/lib/postgresql/data
